### ISSUE TITLE
Add IEX favicon

### ISSUE THREAD

**Issue by acohen** [interexchange/howto#29]
http://howto.interexchange.io does not have a icon on the tab or bookmarks bar

![image](https://cloud.githubusercontent.com/assets/6463784/6807047/82abc64e-d222-11e4-8db6-ae39c85f1494.png)

**Comment by acohen** [comment]
hi @dirkkelly

**Comment by dirkkelly** [comment]
Roger @acohen. Cheers.

**Comment by acohen** [comment]
done

**Comment by acohen** [comment]
#50
